highlight-font: '"GT Walsheim", "gt_walsheim_regular", "Avant Garde Gothic ITCW01Dm", "Avant Garde", "Helvetica Neue", "Arial" '
body: '"Helvetica Neue", "Arial", san-serif'
code: '"Monaco", "Menlo", "Consolas", "Courier New", monospace'

highlight-color: "#000000"
highlight-dark-color: "#737373"
darker-color: "#878787"
darker-dark-color: "#A8A8A8"
background-color: "#D9D9D9"
alt-link-color: "#0008FF"
warning-color: "#FF8800"