codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
ignore:
  - "SwiftyAttributesTests"
coverage:
  precision: 2
  range: "70...99"
  round: down
  status:
    changes: false
    patch:
      default:
        target: 95
    project:
      default:
        target: 99
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
